## Task3

### Step 1:

In [52]:
import pandas as pd
import numpy as np
"""
If blue team wins(1), then red team win will be 0. For such paired columns, we can combine them into one column; the value can be "blue"/"red"/"noteam"
If there is a tie (game duration will for sure smaller than 300s), the row is an outlier and will be dropped. 

KDA=(kill+assist)/death; It is usually for a single player, but in this project it will be calculated and used from a team's aspect. 
KDA is useful to combine and repersent the information from kill, assist and death. But when death=0, KDA should not be calculated(divided by 0). 
To handle such situation, we can simplely drop such rows because death=0 happens when one team is overpoweful or someone disconnected during the game. 
Such situation can be considered as outliers and should be dropped. Same thing can happend if game is too short (<16min (960s))
"""

"""
This chain will first read the dataset, rename the game duration column, and drop null values. After that, it will created two
columns to save KDA for both teams using blue's/red's kill, assist, and death columns. Next, it will drop overliers and combine the info for paired columns.
Finally, it will drop useless columns(including columns of no interest). 
"""

lol1 = (pd.read_csv('../data/raw/Master_Ranked_Games.csv')
      .rename(columns={'gameDuraton':'duration'})
      .dropna()
       )
lol2 = (lol1.assign(blueKDA=lambda x: (x['blueKills']+x['blueAssist'])/x['blueDeath'])
        .assign(redKDA=lambda x: (x['redKills']+x['redAssist'])/x['redDeath'])
        .drop(lol1[(lol1['blueDeath']==0)|(lol1['redDeath']==0)|(lol1['blueKills']==0)|(lol1['redKills']==0)|(lol1['duration']<960)].index) #drop outliers
        .assign(teamFirstBlood = lambda x: np.where(x.blueFirstBlood==1,'blue','red'))
        .assign(teamFirstTower = lambda x: np.where(x.blueFirstTower==1,'blue',(np.where(x.redFirstTower==1,'red','noTeam'))))
        .assign(teamFirstBaron = lambda x: np.where(x.blueFirstBaron==1,'blue',(np.where(x.redFirstBaron==1,'red','noTeam'))))
        .assign(teamFirstDragon = lambda x: np.where(x.blueFirstDragon==1,'blue',(np.where(x.redFirstDragon==1,'red','noTeam'))))
        .assign(teamFirstInhibitor = lambda x: np.where(x.blueFirstInhibitor==1,'blue',(np.where(x.redFirstInhibitor==1,'red','noTeam'))))
        .assign(teamWins = lambda x: np.where(x.blueWins==1,'blue','red'))
        .drop(columns={'gameId','blueWins', 'blueFirstBlood', 'blueFirstTower', 'blueFirstBaron', 'blueFirstDragon',  'blueFirstInhibitor',
                       'redWins', 'redFirstBlood', 'redFirstTower', 'redFirstBaron', 'redFirstDragon',  'redFirstInhibitor', 'blueJungleMinionKills', 
                       'redJungleMinionKills','blueKills', 'blueAssist', 'blueDeath', 'redKills', 'redAssist', 'redDeath', 
                       'blueTotalLevel', 'redTotalLevel'}) #drop now useless or no interesting columns
        .reset_index() 
        .drop(columns='index')
       )
        
lol2

,duration,blueDragonKills,blueBaronKills,blueTowerKills,blueInhibitorKills,blueWardPlaced,blueWardkills,blueChampionDamageDealt,blueTotalGold,blueTotalMinionKills,...,redTotalHeal,redObjectDamageDealt,blueKDA,redKDA,teamFirstBlood,teamFirstTower,teamFirstBaron,teamFirstDragon,teamFirstInhibitor,teamWins
0,1429,0,0,4,0,75,33,42979,41910,646,...,12916,26338,1.052632,9.142857,blue,blue,noTeam,red,noTeam,red
1,1313,0,0,3,0,45,13,36087,35880,563,...,12252,29828,0.681818,10.833333,red,blue,noTeam,red,noTeam,red
2,1660,1,1,9,2,66,31,64708,58214,651,...,17005,37066,7.000000,1.166667,red,red,blue,blue,blue,blue
3,984,2,0,5,0,55,9,45772,36545,402,...,10499,3085,20.000000,0.307692,blue,blue,noTeam,blue,noTeam,blue
4,1437,2,0,3,0,75,23,79501,42395,528,...,47523,47150,1.708333,3.263158,blue,blue,noTeam,blue,noTeam,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90493,1659,4,0,7,1,91,37,82134,53753,553,...,31297,41513,3.909091,1.485714,red,blue,red,blue,blue,blue
90494,2479,3,1,7,1,126,63,142725,82466,803,...,34890,62124,5.000000,1.571429,blue,red,red,red,red,blue
90495,2081,1,0,6,0,91,44,80643,65433,764,...,33499,79612,1.648649,4.200000,blue,blue,red,red,red,red
90496,1619,1,0,2,0,65,10,80053,44680,504,...,52292,60903,1.414634,4.739130,red,red,red,red,red,red
90497,1129,1,0,6,1,41,12,48427,37603,426,...,12749,8035,7.166667,0.588235,red,blue,noTeam,red,blue,blue

### Step 2:

In [54]:
#If blue team wins(1), then red team win will be 0. For such paired columns, we can combine them into one column(eg. teamWins).
#0 for red team, 1 for blue team

"""
If blue team wins(1), then red team win will be 0. For such paired columns, we can combine them into one column; the value can be "blue"/"red"/"noteam"
If there is a tie (game duration will for sure smaller than 300s), the row is an outlier and will be dropped. 

KDA=(kill+assist)/death; It is usually for a single player, but in this project it will be calculated and used from a team's aspect. 
KDA is useful to combine and repersent the information from kill, assist and death. But when death=0, KDA should not be calculated(divided by 0). 
To handle such situation, we can simplely drop such rows because death=0 happens when one team is overpoweful or someone disconnected during the game. 
Such situation can be considered as outliers and should be dropped. Same thing can happend if game is too short (<16min (960s))
"""

def load_and_process(url_or_path_to_csv_file):

    # Method Chain 1 (Load data and deal with missing data)

    lol1 = (pd.read_csv('../data/raw/Master_Ranked_Games.csv')
      .rename(columns={'gameDuraton':'duration'})
      .dropna()
       )

    # Method Chain 2 (Create new columns, drop others, and do processing)

    lol2 = (lol1.assign(blueKDA=lambda x: (x['blueKills']+x['blueAssist'])/x['blueDeath'])
        .assign(redKDA=lambda x: (x['redKills']+x['redAssist'])/x['redDeath'])
        .drop(lol1[(lol1['blueDeath']==0)|(lol1['redDeath']==0)|(lol1['blueKills']==0)|(lol1['redKills']==0)|(lol1['duration']<960)].index) #drop outliers
        .assign(teamFirstBlood = lambda x: np.where(x.blueFirstBlood==1,'blue','red'))
        .assign(teamFirstTower = lambda x: np.where(x.blueFirstTower==1,'blue',(np.where(x.redFirstTower==1,'red','noTeam'))))
        .assign(teamFirstBaron = lambda x: np.where(x.blueFirstBaron==1,'blue',(np.where(x.redFirstBaron==1,'red','noTeam'))))
        .assign(teamFirstDragon = lambda x: np.where(x.blueFirstDragon==1,'blue',(np.where(x.redFirstDragon==1,'red','noTeam'))))
        .assign(teamFirstInhibitor = lambda x: np.where(x.blueFirstInhibitor==1,'blue',(np.where(x.redFirstInhibitor==1,'red','noTeam'))))
        .assign(teamWins = lambda x: np.where(x.blueWins==1,'blue','red'))
        .drop(columns={'gameId','blueWins', 'blueFirstBlood', 'blueFirstTower', 'blueFirstBaron', 'blueFirstDragon',  'blueFirstInhibitor',
                       'redWins', 'redFirstBlood', 'redFirstTower', 'redFirstBaron', 'redFirstDragon',  'redFirstInhibitor', 'blueJungleMinionKills', 
                       'redJungleMinionKills','blueKills', 'blueAssist', 'blueDeath', 'redKills', 'redAssist', 'redDeath', 
                       'blueTotalLevel', 'redTotalLevel'}) #drop now useless or no interesting columns
        .reset_index() 
        .drop(columns='index')
       )

    return lol2

load_and_process('../data/raw/Master_Ranked_Games.csv')

,duration,blueDragonKills,blueBaronKills,blueTowerKills,blueInhibitorKills,blueWardPlaced,blueWardkills,blueChampionDamageDealt,blueTotalGold,blueTotalMinionKills,...,redTotalHeal,redObjectDamageDealt,blueKDA,redKDA,teamFirstBlood,teamFirstTower,teamFirstBaron,teamFirstDragon,teamFirstInhibitor,teamWins
0,1429,0,0,4,0,75,33,42979,41910,646,...,12916,26338,1.052632,9.142857,blue,blue,noTeam,red,noTeam,red
1,1313,0,0,3,0,45,13,36087,35880,563,...,12252,29828,0.681818,10.833333,red,blue,noTeam,red,noTeam,red
2,1660,1,1,9,2,66,31,64708,58214,651,...,17005,37066,7.000000,1.166667,red,red,blue,blue,blue,blue
3,984,2,0,5,0,55,9,45772,36545,402,...,10499,3085,20.000000,0.307692,blue,blue,noTeam,blue,noTeam,blue
4,1437,2,0,3,0,75,23,79501,42395,528,...,47523,47150,1.708333,3.263158,blue,blue,noTeam,blue,noTeam,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90493,1659,4,0,7,1,91,37,82134,53753,553,...,31297,41513,3.909091,1.485714,red,blue,red,blue,blue,blue
90494,2479,3,1,7,1,126,63,142725,82466,803,...,34890,62124,5.000000,1.571429,blue,red,red,red,red,blue
90495,2081,1,0,6,0,91,44,80643,65433,764,...,33499,79612,1.648649,4.200000,blue,blue,red,red,red,red
90496,1619,1,0,2,0,65,10,80053,44680,504,...,52292,60903,1.414634,4.739130,red,red,red,red,red,red
90497,1129,1,0,6,1,41,12,48427,37603,426,...,12749,8035,7.166667,0.588235,red,blue,noTeam,red,blue,blue