In [1]:
from scripts import project_functions 
df = project_functions.load_and_process('../data/raw/Master_Ranked_Games.csv')
df

,duration,blueDragonKills,blueBaronKills,blueTowerKills,blueInhibitorKills,blueWardPlaced,blueWardkills,blueChampionDamageDealt,blueTotalGold,blueTotalMinionKills,...,redTotalHeal,redObjectDamageDealt,blueKDA,redKDA,teamFirstBlood,teamFirstTower,teamFirstBaron,teamFirstDragon,teamFirstInhibitor,teamWins
0,1429,0,0,4,0,75,33,42979,41910,646,...,12916,26338,1.052632,9.142857,blue,blue,noTeam,red,noTeam,red
1,1313,0,0,3,0,45,13,36087,35880,563,...,12252,29828,0.681818,10.833333,red,blue,noTeam,red,noTeam,red
2,1660,1,1,9,2,66,31,64708,58214,651,...,17005,37066,7.000000,1.166667,red,red,blue,blue,blue,blue
3,984,2,0,5,0,55,9,45772,36545,402,...,10499,3085,20.000000,0.307692,blue,blue,noTeam,blue,noTeam,blue
4,1437,2,0,3,0,75,23,79501,42395,528,...,47523,47150,1.708333,3.263158,blue,blue,noTeam,blue,noTeam,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90493,1659,4,0,7,1,91,37,82134,53753,553,...,31297,41513,3.909091,1.485714,red,blue,red,blue,blue,blue
90494,2479,3,1,7,1,126,63,142725,82466,803,...,34890,62124,5.000000,1.571429,blue,red,red,red,red,blue
90495,2081,1,0,6,0,91,44,80643,65433,764,...,33499,79612,1.648649,4.200000,blue,blue,red,red,red,red
90496,1619,1,0,2,0,65,10,80053,44680,504,...,52292,60903,1.414634,4.739130,red,red,red,red,red,red
90497,1129,1,0,6,1,41,12,48427,37603,426,...,12749,8035,7.166667,0.588235,red,blue,noTeam,red,blue,blue